  Running command pip subprocess to install build dependencies
  Using pip 25.2 from C:\projects\python\pdf_contract_masking\.conda_env\Lib\site-packages\pip (python 3.11)
  Collecting setuptools>=61.0
    Obtaining dependency information for setuptools>=61.0 from https://files.pythonhosted.org/packages/a3/dc/17031897dae0efacfea57dfd3a82fdd2a2aeb58e0ff71b77b87e44edc772/setuptools-80.9.0-py3-none-any.whl.metadata
    Using cached setuptools-80.9.0-py3-none-any.whl.metadata (6.6 kB)
  Collecting wheel
    Obtaining dependency information for wheel from https://files.pythonhosted.org/packages/0b/2c/87f3254fd8ffd29e4c02732eee68a83a1d3c346ae39bc6822dcbcb697f2b/wheel-0.45.1-py3-none-any.whl.metadata
    Using cached wheel-0.45.1-py3-none-any.whl.metadata (2.3 kB)
  Using cached setuptools-80.9.0-py3-none-any.whl (1.2 MB)
  Using cached wheel-0.45.1-py3-none-any.whl (72 kB)
  Installing collected packages: wheel, setuptools
    Creating C:\Users\ASUS\AppData\Local\Temp\pip-build-env-_uuvdtfd\overlay\Scripts

  Successfully installed setuptools-80.9.0 wheel-0.45.1
  Running command Checking if build backend supports build_editable
  Running command Getting requirements to build editable
  configuration error: `project.authors[0]` must be object
  GIVEN VALUE:
      "you <you@example.com>"

  OFFENDING RULE: 'type'

  DEFINITION:
      {
          "$id": "#/definitions/author",
          "title": "Author or Maintainer",
          "$comment": "https://peps.python.org/pep-0621/#authors-maintainers",
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "name": {
                  "type": "string",
                  "$$description": [
                      "MUST be a valid email name, i.e. whatever can be put as a name, before an",
                      "email, in :rfc:`822`."
                  ]
              },
              "email": {
                  "type": "string",
                  "format": "idn-email",
                  "description": "MUST be a valid email address"
              }
          }
      }

  For more details about `format` see
  https://validate-pyproject.readthedocs.io/en/latest/api/validate_pyproject.formats.html

  Traceback (most recent call last):
    File "C:\projects\python\pdf_contract_masking\.conda_env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 389, in <module>
      main()
    File "C:\projects\python\pdf_contract_masking\.conda_env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 373, in main
      json_out["return_val"] = hook(**hook_input["kwargs"])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\projects\python\pdf_contract_masking\.conda_env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 157, in get_requires_for_build_editable
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\ASUS\AppData\Local\Temp\pip-build-env-_uuvdtfd\overlay\Lib\site-packages\setuptools\build_meta.py", line 473, in get_requires_for_build_editable
      return self.get_requires_for_build_wheel(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\ASUS\AppData\Local\Temp\pip-build-env-_uuvdtfd\overlay\Lib\site-packages\setuptools\build_meta.py", line 331, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=[])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\ASUS\AppData\Local\Temp\pip-build-env-_uuvdtfd\overlay\Lib\site-packages\setuptools\build_meta.py", line 301, in _get_build_requires
      self.run_setup()
    File "C:\Users\ASUS\AppData\Local\Temp\pip-build-env-_uuvdtfd\overlay\Lib\site-packages\setuptools\build_meta.py", line 317, in run_setup
      exec(code, locals())
    File "<string>", line 1, in <module>
    File "C:\Users\ASUS\AppData\Local\Temp\pip-build-env-_uuvdtfd\overlay\Lib\site-packages\setuptools\__init__.py", line 115, in setup
      return distutils.core.setup(**attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\ASUS\AppData\Local\Temp\pip-build-env-_uuvdtfd\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 160, in setup
      dist.parse_config_files()
    File "C:\Users\ASUS\AppData\Local\Temp\pip-build-env-_uuvdtfd\overlay\Lib\site-packages\setuptools\dist.py", line 756, in parse_config_files
      pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
    File "C:\Users\ASUS\AppData\Local\Temp\pip-build-env-_uuvdtfd\overlay\Lib\site-packages\setuptools\config\pyprojecttoml.py", line 72, in apply_configuration
      config = read_configuration(filepath, True, ignore_option_errors, dist)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\ASUS\AppData\Local\Temp\pip-build-env-_uuvdtfd\overlay\Lib\site-packages\setuptools\config\pyprojecttoml.py", line 140, in read_configuration
      validate(subset, filepath)
    File "C:\Users\ASUS\AppData\Local\Temp\pip-build-env-_uuvdtfd\overlay\Lib\site-packages\setuptools\config\pyprojecttoml.py", line 61, in validate
      raise ValueError(f"{error}\n{summary}") from None
  ValueError: invalid pyproject.toml config: `project.authors[0]`.
  configuration error: `project.authors[0]` must be object
  error: subprocess-exited-with-error
  
  ├ù Getting requirements to build editable did not run successfully.
  Γöé exit code: 1
  Γò░ΓöÇ> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: 'C:\projects\python\pdf_contract_masking\.conda_env\python.exe' 'C:\projects\python\pdf_contract_masking\.conda_env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py' get_requires_for_build_editable 'C:\Users\ASUS\AppData\Local\Temp\tmpcyha01p9'
  cwd: C:\projects\python\pdf_contract_masking
error: subprocess-exited-with-error

├ù Getting requirements to build editable did not run successfully.
Γöé exit code: 1
Γò░ΓöÇ> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

ERROR conda.cli.main_run:execute(127): `conda run python -m pip install -e . -v` failed. (See above for error)
Using pip 25.2 from C:\projects\python\pdf_contract_masking\.conda_env\Lib\site-packages\pip (python 3.11)
Obtaining file:///C:/projects/python/pdf_contract_masking
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build editable: started
  Getting requirements to build editable: finished with status 'error'

